ALTER TABLE orders
    MODIFY COLUMN status ENUM('PENDING', 'PAID', 'NON PAID') NOT NULL DEFAULT 'PENDING';

UPDATE orders
SET status = 'PENDING'
WHERE status = 'NON PAID';

ALTER TABLE orders
    MODIFY COLUMN status ENUM('PENDING', 'PAID') NOT NULL DEFAULT 'PENDING';
